### ISSUE TITLE
Add annotation to Roles Controller

### ISSUE THREAD

**Issue by RickDaniel** [TypecastException/AspNetGroupBasedPermissions#1]
Thank you for this epic example. It is incredibly useful and your blog posts were outstanding.

Tiny comments:
On the Account / Index view, I changed the title from Index to Users for consistency.
I added an annotation to the Index action in the Roles Controller [Authorize(Roles = "Admin")]. Without it, the permissions list was visible to everyone.

These are trivial really, just thought I would pass them along.

**Comment by xivSolutions** [comment]
Awesome, thanks! I can tune it up, for sure, or if you have a PR ready, I'm happy to merge it . . .

**Comment by xivSolutions** [comment]
Nice, thanks man!
