### ISSUE TITLE
Normal user can't change password

### ISSUE THREAD

**Issue by riverstore** [TypecastException/AspNetGroupBasedPermissions#10]
Hi!

First I d'like to say thanks for the usefull code. I'm trying to use this code, on testing, I found that normal users can't change their password (it show the login form). Can anyone please help me. 

Thanks a lot

**Comment by xivSolutions** [comment]
Hmmm . . .

I wasn't really paying attention to that, as my focus was on making the groups thing work. 

I can see about putting in a fix, or, if you wanted to get it working and shoot me a PR, that would be terrific!

I suspect all you need to do is add "User" to the list of roles in the `[Authorize]` attribute decorating teh `Manage()` method on `AccountController`. 

I am a little short on time to investigate tonight, but if you want to try a few things out, I would LOVE your PR...

Thanks!

**Comment by riverstore** [comment]
Hi! Thanks for responding and sorry for any misunderstanding. I'm new to ASP.NET MVC and my English skill is not really good, I just have a problem on using the code and I'd like to ask for helping. If my words make you feel discomfort, I'd like to sorry for that :(.

And if you don't bothering, I'd to ask for more ^^. 
- I see that when normal users trying to access a page that he don't have the permission, the login form will appear (even he logged in), Is there anyway to display a error message instead of the login form
- I'd like to display menu item by user role, I used this method to get user's roles
  Roles.GetRolesForUser()
  but I get error message
  [ProviderException: The Role Manager feature has not been enabled.]

Please help me, thanks a lot

**Comment by xivSolutions** [comment]
I'll try to look into this, but it may be a few days...I'm off to work. 

No discomfort, :-)

**Comment by riverstore** [comment]
Hi! How are you? I'm still waiting for you :P

**Comment by xivSolutions** [comment]
@riverstore -  Ok. This should work for you now. You will need to re-seed the database (this can be a bit of a pain - I'll need to refine the approach on this. Basically, delete the existing Db, modify the Conn string name, and use Package Manager Console `Update-Database`. See the blog post for details on this. 

You will note, I added a plain vanilla user in the `Seed()` method, and then add that user to the "Users" group. 

Then, I updated the `[Authorize]` attribute on the `Manage()` method (both overloads) to include "Users". 

Review the actual commits to see what changed. 

FYI, you may want to see the newer version of this project which uses Identity 2.0. This one uses Identity 1.0, and the newer version of Identity has a lot more to offer. Also, the Db/Migration is implemented as part of the build process in that one. 

See this post [ASP.NET Identity 2.0: Implementing Group-Based Permissions Management](http://typecastexception.com/post/2014/08/10/ASPNET-Identity-20-Implementing-Group-Based-Permissions-Management.aspx) and this Github Repo: [AspNetIdentity2GroupPermissions](https://github.com/TypecastException/AspNetIdentity2GroupPermissions).
