### ISSUE TITLE
Issue when upgrading to Identity 2.0

### ISSUE THREAD

**Issue by tuppers360** [TypecastException/AspNetGroupBasedPermissions#6]
Hi,

Having a problem with the method ClearUserRoles when I upgrade to the Identity 2.0 RTM

The error is on the following line:
_userManager.RemoveFromRole(userId, role.Role.RoleId);

Receive the following error:
Error   2   'Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole' does not contain a definition for 'Role' and no extension method 'Role' accepting a first argument of type 'Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole' could be found (are you missing a using directive or an assembly reference?)

From what I can gather IdentityUserRole has changed not allowing the above code. Not sure how to get around this. Any ideas?

**Comment by xivSolutions** [comment]
Working on a version of this same project for Identity 2.0 as we speak. I'll update this issue when I have it up. 

Indeed, there are a number of breaking changes in Identity 2.0. Meantime, if you have already figured some work-arounds out, would be happy to see what you've done. If so, feel free to do a PR here. I probably won't merge it, as I think a separate project is needed for Identity 2.0. But a PR here will help highlight the important bits.

**Comment by tuppers360** [comment]
Thanks for the swift reply. I am very new but am looking at a few things will let you know.

**Comment by tuppers360** [comment]
From looking at the code the only part that there is an issue is the following:

public void ClearUserRoles(string userId)
        {
            ApplicationUser user = _userManager.FindById(userId);
            var currentRoles = new List<IdentityUserRole>();

```
        currentRoles.AddRange(user.Roles);
        foreach (IdentityUserRole role in currentRoles)
        {
            _userManager.RemoveFromRole(userId, role.Role.Name);
        }
    }
```

due to a change in the IdentityUserRole implementation there is no:
public virtual IdentityRole Role { get; set; }

So there is no way to pass the role name using role.Role.Name

This is where I am at with it all. Looks like there rest of the implementation is ok and will work.

**Comment by xivSolutions** [comment]
Yeah, from what I have seen, IdentityUserRole now simply contains the User
Id and the Role Id, and not references to each object. Seems like possibly
an easy fix.

:-)

**Comment by tuppers360** [comment]
HI,

Well I have almost implemented the solution using the new Identity 2.0 RTM

To change the code above I have amended the ClearUserRoles issue with the following:

```
  public void ClearUserRoles(string userId)
  {
        ApplicationUser user = _userManager.FindById(userId);

        foreach (IdentityUserRole role in user.Roles)
        {
            _userManager.RemoveFromRole(userId, _roleManager.FindById(userId).Name);
        }
  }
```

whilst it is not the cleanest more than likely it works. I do have another error in one of the ViewModels but I will post about that once I have had a good look. Just in the middle of testing.

**Comment by xivSolutions** [comment]
Hey, getting things working is the first step. Careful there - you are passing `userId` into `_roleManager.FindById`, not the `Role.Id`. I can't test this at the moment, but might you mean:

```
    foreach (IdentityUserRole role in user.Roles)
    {
        _userManager.RemoveFromRole(userId, role.Name);
    }
```

Maybe I missed something there - it is early here, and I haven't had my coffee yet. :-)

**Comment by tuppers360** [comment]
Of course! I see what you mean. I will have a look later gardening at the minute! 

Enjoy the coffee!

**Comment by kastimdev** [comment]
Any updates yet on Identity 2.0?

**Comment by xivSolutions** [comment]
Not yet. Taking a little bit to get to that, as I have some other stuff in
progress as well.

We shall see what happens tonight and tomorrow, but realistically, each of
those posts took several days (I do this stuff in my "free time" so it has
to fit in around my day job and such).

I'm hustlin'!  :-)

**Comment by kastimdev** [comment]
Ye I take my hat off to you .... super comprehensive and impressive articles. Only realised when I posted the comment that you mentioned only 4 days ago that you busy with v2, sorry if felt like Im pushy :) ....

**Comment by xivSolutions** [comment]
Nope, not at all!

And, as I've said, if you have any suggestions or helpful code, add an issue, or shoot a PR here, and I will incorporate into the V2 project with credit. :-)

**Comment by kastimdev** [comment]
Its been quite a learning curve for me recently. Developing system with Microsoft Unity Dependency Injection, with EF Database First using using multiple contexts (each user get's own database generated) - had to split the Context classes to separate projects overriding the T4 templates as following Separation of Concern via a repository with each context using it's own Unit of Work ... a month ago I think this previous sentence would have been completely Greek to me :). It's been fun but definitely you gotta "accept" the magic that Unity does when instantiating controllers with  customized constructors when you don't physically instantiate them anywhere.

**Comment by xivSolutions** [comment]
That's awesome! Gotta love learning!

Yeah, the behind the scenes "magic" is annoying as hell until you understand what's going on. One of the biggest challenges in learning MVC and how to use EF is so much happens "behind the scenes" under many layers of abstraction. 

FWIW, this gets even "worse" with Identity 2.0, from what I've seen so far . . . lots of "go to definition" followed by breaking our reflector or Telerik's JustDecompile just to know what's happening :-)

**Comment by jmarkling** [comment]
When can we expect version 2 ? looking forward to it :)

**Comment by xivSolutions** [comment]
@jmarkling - Sorry mate! I've had a TON of work-travel the past month + 

Trying to get back to it  :-)

**Comment by xivSolutions** [comment]
All - 

I've created a new post related to customizing Users and Roles under Identity 2.0. It doesn't repeat the specifics of creating the groups yet, but most of that should be relatively the same once the Users/Roles issues are addressed. 

To get started, see the post [ASP.NET Identity 2.0: Customizing Users and Roles](http://typecastexception.com/post/2014/06/22/ASPNET-Identity-20-Customizing-Users-and-Roles.aspx) and the associated code in the new repo [HERE](https://github.com/TypecastException/AspNet-Identity-2-Extending-Users-And-Roles)

I will likely make a port of the Groups stuff shortly, but I was considering trying out a claims-based approach to that first.
